character(aristocrate).
character(bard).
character(clown).
character(cultist).
character(spirit).
character(healer).
character(king).
character(mask).
character(poprigunchik).
character(prince).
character(princess).
character(snow).
character(mohawk).
character(child).
character(oldman).
character(doll).
