/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import royaltraitor.RoyalTraitor;
import logic.Character;
import logic.Dice;

/**
 *
 * @author bryan
 */
public class MainView extends javax.swing.JFrame {
    boolean f = true;
    private String playerDecision;
    public MainView() {
        this.playerDecision = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public String getPlayerDecision() {
        return playerDecision;
    }

    public void setPlayerDecision(String playerDecision) {
        this.playerDecision = playerDecision;
    }
//@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackground = new javax.swing.JLabel();
        jButtonDice1 = new javax.swing.JButton();
        jLabelClickDices = new javax.swing.JLabel();
        jButtonDice2 = new javax.swing.JButton();
        jButtonDice3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDiceInfo = new javax.swing.JTextArea();
        jTextFieldThiefName = new javax.swing.JTextField();
        jLabelThiefName = new javax.swing.JLabel();
        jLabelSearchFor = new javax.swing.JLabel();
        jButtonClueOption = new javax.swing.JButton();
        jButtonSuspectOption = new javax.swing.JButton();
        jButtonCheckSuspectName = new javax.swing.JButton();
        jButtonRollDice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbackground.setPreferredSize(new java.awt.Dimension(792, 504));

        jButtonDice1.setEnabled(false);
        jButtonDice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDice1ActionPerformed(evt);
            }
        });

        jLabelClickDices.setText("Click to roll dices!");

        jButtonDice2.setEnabled(false);
        jButtonDice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDice2ActionPerformed(evt);
            }
        });

        jButtonDice3.setEnabled(false);
        jButtonDice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDice3ActionPerformed(evt);
            }
        });

        jTextAreaDiceInfo.setColumns(20);
        jTextAreaDiceInfo.setRows(5);
        jTextAreaDiceInfo.setText("2 eyes -> show clue\n2 paws -> show two cards\n                \nOther case -> thief moves");
        jScrollPane1.setViewportView(jTextAreaDiceInfo);

        jTextFieldThiefName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldThiefNameActionPerformed(evt);
            }
        });

        jLabelThiefName.setText("Did you find the thief?  Write its name");

        jLabelSearchFor.setText("Search for");

        jButtonClueOption.setText("Clues");
        jButtonClueOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClueOptionActionPerformed(evt);
            }
        });

        jButtonSuspectOption.setText("Suspects");
        jButtonSuspectOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuspectOptionActionPerformed(evt);
            }
        });

        jButtonCheckSuspectName.setText("Check");
        jButtonCheckSuspectName.setEnabled(false);

        jButtonRollDice.setText("Roll");
        jButtonRollDice.setEnabled(false);
        jButtonRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRollDiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelThiefName)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldThiefName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonDice3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelClickDices)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabelSearchFor)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButtonClueOption)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonSuspectOption))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jButtonCheckSuspectName)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelSearchFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonClueOption)
                            .addComponent(jButtonSuspectOption))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClickDices)
                            .addComponent(jButtonRollDice))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDice2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonDice3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jTextFieldThiefName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelThiefName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCheckSuspectName))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldThiefNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldThiefNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldThiefNameActionPerformed

    private void jButtonDice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDice3ActionPerformed

    private void jButtonDice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDice1ActionPerformed
        // TODO add your handling code here:
        //this.jButtonDice2.setEnabled(true);
    }//GEN-LAST:event_jButtonDice1ActionPerformed

    private void jButtonDice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDice2ActionPerformed
        // TODO add your handling code here:
        //this.jButtonDice3.setEnabled(true);
    }//GEN-LAST:event_jButtonDice2ActionPerformed

    private void jButtonClueOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClueOptionActionPerformed
        // TODO add your handling code here:
        this.jButtonSuspectOption.setEnabled(false);
        setPlayerDecision("paw");
        this.jButtonRollDice.setEnabled(true);
        this.jButtonDice1.setEnabled(true);
        this.jButtonDice2.setEnabled(true);
        this.jButtonDice3.setEnabled(true);
        //ImageIcon imageForOne = new ImageIcon(getClass().getResource("/view/resources/others/brain.png"));
        //this.jButtonDice1.setIcon(imageForOne); 
    }//GEN-LAST:event_jButtonClueOptionActionPerformed

    private void jButtonSuspectOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuspectOptionActionPerformed
        // TODO add your handling code here:
        this.jButtonClueOption.setEnabled(false);
        setPlayerDecision("eye");
        this.jButtonRollDice.setEnabled(true);
        this.jButtonDice1.setEnabled(true);
        this.jButtonDice2.setEnabled(true);
        this.jButtonDice3.setEnabled(true);
    }//GEN-LAST:event_jButtonSuspectOptionActionPerformed

    private void jButtonRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRollDiceActionPerformed
        // TODO add your handling code here:
        //Faltan las 3 tiradas
        //Dado 1 es clue y la decision del jugador tambien
        
        if (this.jButtonDice1.getText() == getPlayerDecision()) {
            // block of code to be executed if condition1 is true
            this.jButtonDice1.setEnabled(false);
            
        }if (this.jButtonDice2.getText() == getPlayerDecision()) {
            // block of code to be executed if condition1 is true
            this.jButtonDice2.setEnabled(false);
            
            
        }if (this.jButtonDice2.getText() == getPlayerDecision()) {
            // block of code to be executed if condition1 is true
            this.jButtonDice2.setEnabled(false);
        }   
            

    }//GEN-LAST:event_jButtonRollDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void initialDraws(ArrayList<Character> characters,ArrayList road){
 
        int iC = 0;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
       
        
        this.jbackground.removeAll();

        ImageIcon backgroundImage = new ImageIcon(RoyalTraitor.class.getResource("/view/resources/Mapa.png"));
        this.jbackground.setIcon(backgroundImage);
        this.jbackground.setSize(792,504);
       
        int posX = 185;//60 inicial
        int posY = 20;//40 inicial
        int charcs = 0;
        for(int i = 0; i<4;i++){
            JLabel p = new JLabel();
            p.setSize(58,72);
            String nameC = "";
            if(characters.get(iC).isUp()){
                nameC = characters.get(iC).getName();
            }else{
                nameC = "question";
            }
            ImageIcon pI = new ImageIcon(RoyalTraitor.class.getResource("/view/resources/characters/"+nameC+".png"));
            p.setIcon(pI);
            p.setLocation(posX, posY);
            posX = posX+120;
            this.jbackground.add(p);
            iC ++;
        }
        posX = 40;
        posY = 100;
        for(int i = 0; i<4;i++){
            JLabel p = new JLabel();
            p.setSize(58,72);
            String nameC = "";
            if(characters.get(iC).isUp()){
                nameC = characters.get(iC).getName();
            }else{
                nameC = "question";
            }
            ImageIcon pI = new ImageIcon(RoyalTraitor.class.getResource("/view/resources/characters/"+nameC+".png"));
            p.setIcon(pI);
            p.setLocation(posX, posY);
            posY = posY+80;
            this.jbackground.add(p);
            iC++;
        }
        
        posX = 185;
        posY = 400;
        for(int i = 0; i<4;i++){
            JLabel p = new JLabel();
            p.setSize(58,72);
            String nameC = "";
            if(characters.get(iC).isUp()){
                nameC = characters.get(iC).getName();
            }else{
                nameC = "question";
            }
            ImageIcon pI = new ImageIcon(RoyalTraitor.class.getResource("/view/resources/characters/"+nameC+".png"));
            p.setIcon(pI);
            p.setLocation(posX, posY);
            posX = posX+120;
            this.jbackground.add(p);
            iC++;
        }
        
        posX = 690;
        posY = 100;
        for(int i = 0; i<4;i++){
            JLabel p = new JLabel();
            p.setSize(58,72);
            String nameC = "";
            if(characters.get(iC).isUp()){
                nameC = characters.get(iC).getName();
            }else{
                nameC = "question";
            }
            ImageIcon pI = new ImageIcon(RoyalTraitor.class.getResource("/view/resources/characters/"+nameC+".png"));
            p.setIcon(pI);
            p.setLocation(posX, posY);
            posY = posY+80;
            this.jbackground.add(p);
            iC++;
        }
        
        posX = 120;
        posY = 145;
        for(int i = 0; i<road.size();i++){
            String nameC = "question";
            
            if (road.get(i).equals(1)){
                nameC = "thiefH";
            }
            
            else if (i == 1||i == 5||i == 10||i == 14){
        
                if (road.get(i).equals(1)){
                nameC = "thiefV";
                }else{
                    nameC = "mud2";
                }
                posY = posY+45;
                posX = posX-45;
            }else{
                    nameC = "mud";
                }
            

            JLabel p = new JLabel();
            p.setSize(45,45);
            ImageIcon pI = new ImageIcon(RoyalTraitor.class.getResource("/view/resources/characters/"+nameC+".png"));
            p.setIcon(pI);
            p.setLocation(posX, posY);
            posX = posX+45;
            
            this.jbackground.add(p);
            

            }
 
        this.jbackground.repaint();
    
    }
   
    public void resizeBackground(){
        this.jbackground.setSize(1100,504);
    }

    public void setDicesFace(String dice1, String dice2, String dice3){
        this.jButtonDice1.setText(dice1);
        this.jButtonDice2.setText(dice2);
        this.jButtonDice3.setText(dice3);
        
    }
    
    public void updateDicesIcons(String dice1, String dice2, String dice3){
        ImageIcon imageForPaw = new ImageIcon(getClass().getResource("/view/resources/others/brain.png"));
        ImageIcon imageForEye = new ImageIcon(getClass().getResource("/view/resources/others/dice.png"));

        if (this.jButtonDice1.getText() == "paw") {
            this.jButtonDice1.setIcon(imageForPaw); 
        } else {
           this.jButtonDice1.setIcon(imageForEye); 
           
        }if (this.jButtonDice2.getText() == "paw") {
            this.jButtonDice2.setIcon(imageForPaw); 
        } else {
           this.jButtonDice2.setIcon(imageForEye);
           
        }if (this.jButtonDice3.getText() == "paw") {
            this.jButtonDice3.setIcon(imageForPaw); 
        } else {
           this.jButtonDice3.setIcon(imageForEye); 
        }

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckSuspectName;
    private javax.swing.JButton jButtonClueOption;
    private javax.swing.JButton jButtonDice1;
    private javax.swing.JButton jButtonDice2;
    private javax.swing.JButton jButtonDice3;
    private javax.swing.JButton jButtonRollDice;
    private javax.swing.JButton jButtonSuspectOption;
    private javax.swing.JLabel jLabelClickDices;
    private javax.swing.JLabel jLabelSearchFor;
    private javax.swing.JLabel jLabelThiefName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDiceInfo;
    private javax.swing.JTextField jTextFieldThiefName;
    private javax.swing.JLabel jbackground;
    // End of variables declaration//GEN-END:variables
}
